### ISSUE TITLE
how to register admin to nacos

### ISSUE THREAD

**Issue by David0339** [apache/incubator-shenyu#1405]
## Question
我想把admin注册到nacos上，但启动时报错配置和信息如下
## Config
soul:
  register:
    registerType: nacos #http #zookeeper #etcd #nacos #consul
    serverLists: localhost:8848 #http://localhost:2379 #localhost:8848
    props:
      sessionTimeout: 5000
      connectionTimeout: 2000
      checked: true
      zombieCheckTimes: 5
      scheduledTime: 10
      nacosNameSpace: public
  database:
    dialect: mysql
    init_script: "META-INF/schema.sql"
    init_enable: false
  sync:
    websocket:
      enabled: true

## error log
Caused by: com.alibaba.nacos.api.exception.NacosException: Request nacos server failed: 
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:213)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.subscribe(NamingGrpcClientProxy.java:172)
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.subscribe(NamingClientProxyDelegate.java:146)
	at com.alibaba.nacos.client.naming.NacosNamingService.selectInstances(NacosNamingService.java:284)
	at com.alibaba.nacos.client.naming.NacosNamingService.selectInstances(NacosNamingService.java:272)
	at com.alibaba.nacos.client.naming.NacosNamingService.selectInstances(NacosNamingService.java:260)
	at com.alibaba.nacos.client.naming.NacosNamingService.selectInstances(NacosNamingService.java:237)
	at org.dromara.soul.register.server.nacos.NacosServerRegisterRepository.subscribeRpcTypeService(NacosServerRegisterRepository.java:111)
	at java.util.Arrays$ArrayList.forEach(Arrays.java:3880)
	at org.dromara.soul.register.server.nacos.NacosServerRegisterRepository.subscribe(NacosServerRegisterRepository.java:103)
	at org.dromara.soul.register.server.nacos.NacosServerRegisterRepository.init(NacosServerRegisterRepository.java:99)
	at org.dromara.soul.admin.config.RegisterCenterConfiguration.soulServerRegisterRepository(RegisterCenterConfiguration.java:64)
	at org.dromara.soul.admin.config.RegisterCenterConfiguration$$EnhancerBySpringCGLIB$$16a100f.CGLIB$soulServerRegisterRepository$1(<generated>)
	at org.dromara.soul.admin.config.RegisterCenterConfiguration$$EnhancerBySpringCGLIB$$16a100f$$FastClassBySpringCGLIB$$89669cd0.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
	at org.dromara.soul.admin.config.RegisterCenterConfiguration$$EnhancerBySpringCGLIB$$16a100f.soulServerRegisterRepository(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 20 common frames omitted

**Comment by WYUSIG** [comment]
What versions of ShenYu and Nacos do you use?

**Comment by David0339** [comment]
soul:2.3.0-RELEASE & nacos: 2.0.1

**Comment by lw1243925457** [comment]
Maybe you nacos server config is incorrect. You can try like this:
