### ISSUE TITLE
click SynchronousData bug

### ISSUE THREAD

**Issue by xh649225370** [apache/incubator-shenyu#1717]
click SynchronousData bug

2021-07-05 19:23:00 [ZkClient-EventThread-72-localhost:2181] ERROR org.I0Itec.zkclient.ZkEventThread - Error handling event ZkEvent[Data of /shenyu/metaData/%2Fdn%2F** changed sent to org.apache.shenyu.sync.data.zookeeper.ZookeeperSyncDataService$5@2f161948]
java.lang.ClassCastException: java.lang.String cannot be cast to org.apache.shenyu.common.dto.MetaData
	at org.apache.shenyu.sync.data.zookeeper.ZookeeperSyncDataService$5.handleDataChange(ZookeeperSyncDataService.java:297)
	at org.I0Itec.zkclient.ZkClient$9.run(ZkClient.java:823)
	at org.I0Itec.zkclient.ZkEventThread.run(ZkEventThread.java:72)

**Comment by KevinClair** [comment]
Please describe in detail, and tell us the version.

**Comment by xh649225370** [comment]
zookeeper Data Synchronization bug

shenyu version:2.4.0-SNAPSHOT

zk version: 3.6.3

useing Zookeeper Synchronization
