### ISSUE TITLE
shenyu-admin login failure

### ISSUE THREAD

**Issue by ShawnJim** [apache/incubator-shenyu#1749]
## Describe the bug

**shenyu-admin** application.yml missing `aes.secret. iv` configuration. Login throw NullPointerException

## Environment

- ShenYu version(s): [e.g. master]

## Debug logs

<details>
<summary>Click to expand</summary>

```
2021-07-11 20:14:48 [http-nio-0.0.0.0-9095-exec-1] INFO  org.apache.shenyu.admin.listener.websocket.WebsocketCollector - websocket on client[127.0.0.1] open successful....
2021-07-11 20:15:04 [http-nio-0.0.0.0-9095-exec-2] ERROR org.apache.shenyu.admin.exception.ExceptionHandlers - java.lang.NullPointerException
org.apache.shenyu.common.exception.ShenyuException: java.lang.NullPointerException
	at org.apache.shenyu.admin.utils.CipherUtils.lambda$encryptHex$0(CipherUtils.java:81)
	at java.base/java.util.Optional.map(Optional.java:265)
	at org.apache.shenyu.admin.utils.CipherUtils.encryptHex(CipherUtils.java:75)
	at org.apache.shenyu.admin.utils.AesUtils.aesEncryption(AesUtils.java:37)
	at org.apache.shenyu.admin.service.impl.DashboardUserServiceImpl.loginByDatabase(DashboardUserServiceImpl.java:244)
	at org.apache.shenyu.admin.service.impl.DashboardUserServiceImpl.login(DashboardUserServiceImpl.java:194)
	at org.apache.shenyu.admin.service.impl.DashboardUserServiceImpl$$FastClassBySpringCGLIB$$e3d6f4e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
```
</details>

**Comment by tydhot** [comment]
Thanks
