### ISSUE TITLE
There is an error when I access the gateway I built

### ISSUE THREAD

**Issue by hqgordon** [apache/incubator-shenyu#1860]
## Question

When I open Shenyu-admin, it is ok to open and access the shenyu-bootstrap gateway in the project, but the following error will be reported when I access the gateway built by myself according to the tutorial。

thanks for help！

2021-08-03 18:17:33.134 ERROR 3622 --- [-work-threads-3] o.d.soul.web.handler.GlobalErrorHandler  : [5e457a57] Resolved [NullPointerException: null] for HTTP GET /test
2021-08-03 18:17:33.135 ERROR 3622 --- [-work-threads-3] a.w.r.e.AbstractErrorWebExceptionHandler : [5e457a57]  500 Server Error for HTTP GET "/test"

java.lang.NullPointerException: null
	at org.dromara.soul.plugin.global.DefaultSoulContextBuilder.build(DefaultSoulContextBuilder.java:63) ~[soul-plugin-global-2.3.0-RELEASE.jar:2.3.0-RELEASE]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ org.dromara.soul.web.configuration.ErrorHandlerConfiguration$1 [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.dromara.soul.web.filter.WebSocketParamFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ shenyu.shenyu.SurenessFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ HTTP GET "/test" [ExceptionHandlingWebHandler]
Stack trace:
		at org.dromara.soul.plugin.global.DefaultSoulContextBuilder.build(DefaultSoulContextBuilder.java:63) ~[soul-plugin-global-2.3.0-RELEASE.jar:2.3.0-RELEASE]
		at org.dromara.soul.plugin.global.GlobalPlugin.execute(GlobalPlugin.java:55) ~[soul-plugin-global-2.3.0-RELEASE.jar:2.3.0-RELEASE]
		at org.dromara.soul.web.handler.SoulWebHandler$DefaultSoulPluginChain.lambda$execute$0(SoulWebHandler.java:100) ~[soul-web-2.3.0-RELEASE.jar:2.3.0-RELEASE]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44) ~[reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4105) ~[reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
		at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:124) ~[reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
		at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
		at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
		at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) ~[na:1.8.0_271]
		at java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:1.8.0_271]
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_271]
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_271]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_271]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_271]
		at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_271]

**Comment by midnight2104** [comment]
hi,   are you based on soul-2.3.0? does your gateway work properly? has a starter package been add?

**Comment by hqgordon** [comment]
> hi, are you based on soul-2.3.0? does your gateway work properly? has a starter package been add?

https://shenyu.apache.org/zh/projects/shenyu-2.3.0/soul-set-up/
Follow the last step to set up your own gateway pom file

**Comment by nuo-promise** [comment]
> > hi, are you based on soul-2.3.0? does your gateway work properly? has a starter package been add?
> 
> https://shenyu.apache.org/zh/projects/shenyu-2.3.0/soul-set-up/
> Follow the last step to set up your own gateway pom file

According to the logs it looks like the http interface /test is missing, can you provide the url you requested from the gateway, and at the same time look in the shenyu-admin to see if there is a corresponding request url configuration for the corresponding plugin's rules and selector you are using.

**Comment by hqgordon** [comment]
rules is right，Question seems to be org. Dromara. Soul. Plugin. Global. DefaultSoulContextBuilder decorator method error, there should be no implementation class

**Comment by nuo-promise** [comment]
Can you provide me with a screenshot of the runtime and configuration, so I
can reproduce it locally?

hqgordon ***@***.***> 于2021年8月4日周三 下午1:54写道：

**Comment by hqgordon** [comment]
All I did was to change the password of mysql in admin and set up the gateway just like the gateway in the web page. In the configuration, I just added the configuration in Divide plugin.

The key point is that I visit any address and it returns a null pointer and 500 rather than bootstrap as I do when I open the project.
"code": -107,
"message": "Can not find selector, please check your configuration!" .
"data": null

Do I think there might be some essential components missing

**Comment by midnight2104** [comment]
Hello, how are you doing? In the 2.3.0 version of the gateway, no plugins are add by default. For Http requests, add the Divide plugin. pls see [http代理](https://shenyu.apache.org/zh/projects/shenyu-2.3.0/http-proxy/) to add dependency.

**Comment by hqgordon** [comment]
> Hello, how are you doing? In the 2.3.0 version of the gateway, no plugins are add by default. For Http requests, add the Divide plugin. pls see [http proxy](https://shenyu.apache.org/zh/projects/shenyu-2.3.0/http-proxy/) to add dependency.

thanks!!!!!!!!!!!!!!!!!!!!it really helps!!!!!!!!!!!!
