### ISSUE TITLE
Redirect Plugin application inner redirect 'NOT_FOUND'

### ISSUE THREAD

**Issue by qicz** [apache/incubator-shenyu#2028]
## Describe the bug
set `/goods` redirect to `/user`, but the redirect request `uri` is invalid.

## Environment

- ShenYu version(s): 2.4.1-SNAPSHOT

## Expected behavior
![image](https://user-images.githubusercontent.com/2174082/132116835-8057b881-5160-477e-ba81-8afc2ee82462.png)

## Debug logs

<details>
<summary>Click to expand</summary>

```
2021-09-05 13:47:03 [shenyu-netty-kqueue-4] INFO  org.apache.shenyu.plugin.base.AbstractShenyuPlugin - redirect selector success match , selector name :/goods
2021-09-05 13:47:03 [shenyu-netty-kqueue-4] INFO  org.apache.shenyu.plugin.base.AbstractShenyuPlugin - redirect rule success match , rule name :/user
2021-09-05 13:47:07 [shenyu-netty-kqueue-4] ERROR org.apache.shenyu.web.handler.GlobalErrorHandler - [bce9c618] Resolved [ResponseStatusException: 404 NOT_FOUND] for HTTP GET /goods
2021-09-05 13:47:07 [shenyu-netty-kqueue-4] INFO  org.openingo.jdkits.lang.ThreadShareKit - getRemove data f8028678-3d38-411a-b745-76cf3ae80eda with name Request-Id
2021-09-05 13:47:07 [shenyu-netty-kqueue-4] ERROR org.springframework.boot.autoconfigure.web.reactive.error.AbstractErrorWebExceptionHandler - [bce9c618]  500 Server Error for HTTP GET "/goods"
org.springframework.web.server.ResponseStatusException: 404 NOT_FOUND
	at org.springframework.web.reactive.resource.ResourceWebHandler.lambda$handle$0(ResourceWebHandler.java:325)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ org.apache.shenyu.web.configuration.ErrorHandlerConfiguration$1 [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.apache.shenyu.web.filter.WebSocketParamFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.apache.shenyu.web.filter.FileSizeFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.apache.shenyu.bootstrap.filter.HealthFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.apache.shenyu.web.filter.CrossFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.apache.shenyu.web.filter.LocalDispatcherFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ HTTP GET "/goods" [ExceptionHandlingWebHandler]
Stack trace:
		at org.springframework.web.reactive.resource.ResourceWebHandler.lambda$handle$0(ResourceWebHandler.java:325)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
		at reactor.core.publisher.Mono.subscribe(Mono.java:4105)
		at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:75)
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onComplete(MonoFlatMap.java:174)
		at reactor.core.publisher.MonoNext$NextSubscriber.onComplete(MonoNext.java:96)
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:359)
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onSubscribe(FluxConcatMap.java:211)
		at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:139)
		at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:63)
		at reactor.core.publisher.Mono.subscribe(Mono.java:4105)
		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:172)
		at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56)
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
		at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67)
		at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:76)
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.innerNext(FluxConcatMap.java:274)
		at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(FluxConcatMap.java:851)
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
		at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2186)
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:162)
		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:1994)
		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:1868)
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:90)
		at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
		at reactor.core.publisher.Mono.subscribe(Mono.java:4105)
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:441)
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onSubscribe(FluxConcatMap.java:211)
		at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:139)
		at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:63)
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:55)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:55)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
		at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67)
		at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2186)
		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:1994)
		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:1868)
		at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:55)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:55)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:55)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:55)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:55)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:55)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:55)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
		at reactor.core.publisher.Mono.subscribe(Mono.java:4105)
		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:172)
		at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56)
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:55)
		at reactor.netty.http.server.HttpServerHandle.onStateChange(HttpServerHandle.java:64)
		at reactor.netty.tcp.TcpServerBind$ChildObserver.onStateChange(TcpServerBind.java:226)
		at reactor.netty.http.server.HttpServerOperations.onInboundNext(HttpServerOperations.java:441)
		at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:89)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
		at reactor.netty.http.server.HttpTrafficHandler.channelRead(HttpTrafficHandler.java:167)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
		at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
		at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326)
		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:300)
		at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
		at io.netty.channel.kqueue.AbstractKQueueStreamChannel$KQueueStreamUnsafe.readReady(AbstractKQueueStreamChannel.java:544)
		at io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.readReady(AbstractKQueueChannel.java:381)
		at io.netty.channel.kqueue.KQueueEventLoop.processReady(KQueueEventLoop.java:211)
		at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:289)
		at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.lang.Thread.run(Thread.java:748)
```
</details>

**Comment by qicz** [comment]
@Asxing hi, the redirect plugin 's `dispatcherHandler` how to find the `redirectUri` in `shenyu`?

**Comment by ichenhe** [comment]
Encontered the same problem, any updates here?

**Comment by ichenhe** [comment]
I am not familiar with WebFlux, so I can't fix this issue. This is my temporary workaround:

⚠️ This is a hack, for my use case only, has not been fully tested. I hope someone can really fix it.

Copy the Redirect plugin to your gateway, change the part that `startsWith(ROOT_PATH_PREFIX)`:

1. Call the chain normally instead of `dispatcherHandler`.
2. Change `shenyuContext`'s `realUrl` because the spring cloud plugin use this.


```java
// spring cloud plugin use context's realUrl
ShenyuContext shenyuContext = exchange.getAttribute(Constants.CONTEXT);
assert shenyuContext != null;
shenyuContext.setRealUrl(redirectHandle.getRedirectURI());

// do not call dispatcherHandler
return chain.execute(mutated);
```

**Comment by qicz** [comment]
@ichenhe I have discussed this with @yu199195  before . The conclusion is that this is the design logic of the plug-in itself.

the URI start with "/" just support `shenyu` provides the endpoints.

**Comment by ichenhe** [comment]
@qicz Thanks, got it. So, at present, there is no suitable plugin for my usecase (redirect to another url that shoule be processed by backend).

In my opinion, this demand is not very strange, should we consider implementing it?

**Comment by qicz** [comment]
> @qicz Thanks, got it. So, at present, there is no suitable plugin for my usecase (redirect to another url that shoule be processed by backend).
> 
> In my opinion, this demand is not very strange, should we consider implementing it?

As far as I know, the `redirect` process the URI that starts with "/" and in the "shenyu" runtime, like `fallback` endpoints. and another urls the `redirect`  has supported.

**Comment by ichenhe** [comment]
Sorry, but I  don't fully understand your words. What does 'another urls ' and `fallback` mean? Of course, it's also possible that I don't know enough about  Shenyu.

**Comment by qicz** [comment]
> Sorry, but I don't fully understand your words. What does 'another urls ' and `fallback` mean? Of course, it's also possible that I don't know enough about Shenyu.

The "shenyu" runtime means "@Controller" or  "@RestController" in then "Shenyu" endpoints. 

`fallback` endpoints see image:
![image](https://user-images.githubusercontent.com/2174082/135091122-cb9079fd-750c-4afc-92eb-bb59085430e4.png)

**Comment by ichenhe** [comment]
If I understand it correctly, you mean absolute url can be forwarded successfully. But But the relative url (starts with `/`) can only be forwarded to the endpoint provided by Shenyu.

But what I hope is that the relative url can also be forwarded to other backend services, just like your describtion at the beginning of this issue. Can it be improved to achieve it?

**Comment by qicz** [comment]
> If I understand it correctly, you mean absolute url can be forwarded successfully. But the relative url (starts with `/`) can only be forwarded to the endpoint provided by Shenyu.
> 
> But what I hope is that the relative url can also be forwarded to other backend services, just like your describtion at the beginning of this issue. Can it be improved to achieve it?

maybe mapping the `/` URI and backend services achieve it.
