### ISSUE TITLE
[BUG] SpringMvcClientBeanPostProcessor path process error in diferent platform

### ISSUE THREAD

**Issue by qicz** [apache/incubator-shenyu#2184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

run the "shenyu-examples-http", the path process is a fault.

### Expected Behavior

the URI path is invalid.

### Environment

```markdown
ShenYu version(s): 2.4.1-SNAPSHOT
```

### Debug logs

Exception in thread "shenyu-spring-mvc-client-thread-pool-0" java.nio.file.InvalidPathException: Illegal char <*> at index 14: /\/http\/test/**
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at org.apache.shenyu.client.springmvc.init.SpringMvcClientBeanPostProcessor.buildMetaDataDTO(SpringMvcClientBeanPostProcessor.java:127)
	at org.apache.shenyu.client.springmvc.init.SpringMvcClientBeanPostProcessor.lambda$postProcessAfterInitialization$0(SpringMvcClientBeanPostProcessor.java:103)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "shenyu-spring-mvc-client-thread-pool-1" java.nio.file.InvalidPathException: Illegal char <*> at index 21: /\/http\/order\/path/**/name
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at org.apache.shenyu.client.springmvc.init.SpringMvcClientBeanPostProcessor.buildMetaDataDTO(SpringMvcClientBeanPostProcessor.java:127)
	at org.apache.shenyu.client.springmvc.init.SpringMvcClientBeanPostProcessor.lambda$postProcessAfterInitialization$1(SpringMvcClientBeanPostProcessor.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "shenyu-spring-mvc-client-thread-pool-2" java.nio.file.InvalidPathException: Illegal char <*> at index 21: /\/http\/order\/path/**
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at org.apache.shenyu.client.springmvc.init.SpringMvcClientBeanPostProcessor.buildMetaDataDTO(SpringMvcClientBeanPostProcessor.java:127)
	at org.apache.shenyu.client.springmvc.init.SpringMvcClientBeanPostProcessor.lambda$postProcessAfterInitialization$1(SpringMvcClientBeanPostProcessor.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "shenyu-spring-mvc-client-thread-pool-3" java.nio.file.InvalidPathException: Illegal char <*> at index 17: /\/http\/request/**
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at org.apache.shenyu.client.springmvc.init.SpringMvcClientBeanPostProcessor.buildMetaDataDTO(SpringMvcClientBeanPostProcessor.java:127)
	at org.apache.shenyu.client.springmvc.init.SpringMvcClientBeanPostProcessor.lambda$postProcessAfterInitialization$0(SpringMvcClientBeanPostProcessor.java:103)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by qicz** [comment]
@sunrui849 
The `Paths.get` api will use different `FileSystemProvider`, windows start with `\` , Unix like start with `/`, but URI path must use `/`.

![image](https://user-images.githubusercontent.com/2174082/135483594-e10a9f11-3720-40a1-bf77-8a83488ccd07.png)
![image](https://user-images.githubusercontent.com/2174082/135483828-3fbd95d7-e009-42e1-b5e7-30237b4a71f2.png)
