### ISSUE TITLE
[BUG] <title>When the client configuration registerType is Nacos and the ifFull attribute is true, java.lang.NullPointerException: null will occur at this time

### ISSUE THREAD

**Issue by 65725738** [apache/incubator-shenyu#2276]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![图片](https://user-images.githubusercontent.com/12229436/139202980-309953f0-d2ec-4e23-a6d4-573dd0ee384e.png)
springcloud client config：
shenyu:
  client:
    registerType: nacos
    serverLists: localhost:8848
    props:
      contextPath: /winning
      appName: http
      port: 9988  
      isFull: true
      nacosNameSpace: ShenyuRegisterCenter

### Expected Behavior

NullPointerException

### Environment

```markdown
ShenYu version(s):2.4.1
```

### Debug logs

java.lang.NullPointerException: null
	at org.apache.shenyu.client.springcloud.init.ContextRegisterListener.buildMetaDataDTO(ContextRegisterListener.java:110) ~[shenyu-client-springcloud-2.4.1.jar:2.4.1]
	at org.apache.shenyu.client.springcloud.init.ContextRegisterListener.onApplicationEvent(ContextRegisterListener.java:91) ~[shenyu-client-springcloud-2.4.1.jar:2.4.1]
	at org.apache.shenyu.client.springcloud.init.ContextRegisterListener.onApplicationEvent(ContextRegisterListener.java:40) ~[shenyu-client-springcloud-2.4.1.jar:2.4.1]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.2.10.RELEASE.jar:5.2.10.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.2.10.RELEASE.jar:5.2.10.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.2.10.RELEASE.jar:5.2.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:404) ~[spring-context-5.2.10.RELEASE.jar:5.2.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:361) ~[spring-context-5.2.10.RELEASE.jar:5.2.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:898) ~[spring-context-5.2.10.RELEASE.jar:5.2.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:554) ~[spring-context-5.2.10.RELEASE.jar:5.2.10.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[spring-boot-2.3.5.RELEASE.jar:2.3.5.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) ~[spring-boot-2.3.5.RELEASE.jar:2.3.5.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) ~[spring-boot-2.3.5.RELEASE.jar:2.3.5.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:405) ~[spring-boot-2.3.5.RELEASE.jar:2.3.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.3.5.RELEASE.jar:2.3.5.RELEASE]
	at com.badu.common.test.CommomTestBootstrap.main(CommomTestBootstrap.java:13) [classes/:na]

### Anything else?

11

**Comment by KevinClair** [comment]
Hello @65725738 ,i find this problem in branch master, so can you fix it?
