### ISSUE TITLE
[BUG] <Shiro> ShiroProperties.getWhiteList() is null

### ISSUE THREAD

**Issue by nuo-promise** [apache/incubator-shenyu#2413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

ShiroProperties.getWhiteList() is null.

### Environment

```markdown
ShenYu version(s): latest
```

### Debug logs

Caused by: java.lang.NullPointerException: null
	at org.apache.shenyu.admin.shiro.config.ShiroConfiguration.shiroFilterFactoryBean(ShiroConfiguration.java:75) ~[classes/:na]
	at org.apache.shenyu.admin.shiro.config.ShiroConfiguration$$EnhancerBySpringCGLIB$$f1ce345f.CGLIB$shiroFilterFactoryBean$1(<generated>) ~[classes/:na]
	at org.apache.shenyu.admin.shiro.config.ShiroConfiguration$$EnhancerBySpringCGLIB$$f1ce345f$$FastClassBySpringCGLIB$$7a4cd641.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363) ~[spring-context-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.apache.shenyu.admin.shiro.config.ShiroConfiguration$$EnhancerBySpringCGLIB$$f1ce345f.shiroFilterFactoryBean(<generated>) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.2.2.RELEASE.jar:5.2.2.RELEASE]

**Comment by nuo-promise** [comment]
The yml file is not read by the program startup.

**Comment by nuo-promise** [comment]
The problem has not yet been solved.
