### ISSUE TITLE
[Question] websocket example meet 404 error

### ISSUE THREAD

**Issue by PeaceStefanYO** [apache/incubator-shenyu#2809]
### Error stack:
`2022-01-25 16:41:18 [reactor-http-kqueue-3] WARN  reactor.netty.http.client.HttpClientConnect - [id: 0xecf885e6, L:/127.0.0.1:58299 - R:127.0.0.1/127.0.0.1:8868] The connection observed an error
io.netty.handler.codec.http.websocketx.WebSocketHandshakeException: Invalid handshake response getStatus: 404 Not Found
	at io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker13.verify(WebSocketClientHandshaker13.java:267)
	at io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker.finishHandshake(WebSocketClientHandshaker.java:303)
	at reactor.netty.http.client.WebsocketClientOperations.onInboundNext(WebsocketClientOperations.java:117)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:89)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:300)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.kqueue.AbstractKQueueStreamChannel$KQueueStreamUnsafe.readReady(AbstractKQueueStreamChannel.java:544)
	at io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.readReady(AbstractKQueueChannel.java:381)
	at io.netty.channel.kqueue.KQueueEventLoop.processReady(KQueueEventLoop.java:211)
	at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:289)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)`

### My SELECTOR configs:
`handleResult({"groupType":"SELECTOR","eventType":"UPDATE","data":[{"id":"1485518164594327552","pluginId":"26","pluginName":"websocket","name":"websocket-demo","matchMode":0,"type":1,"sort":1,"enabled":true,"logged":true,"continued":true,"handle":"[{\"host\":\"127.0.0.1\",\"url\":\"127.0.0.1:8868\",\"protocol\":\"ws://\",\"weight\":50,\"timestamp\":0,\"warmup\":0,\"status\":true}]","conditionList":[{"paramType":"uri","operator":"match","paramName":"/","paramValue":"/socket/**"}]}]})`

### My RULE configs:
`handleResult({"groupType":"RULE","eventType":"UPDATE","data":[{"id":"1485536123337375744","name":"socket-test规则","pluginName":"websocket","selectorId":"1485518164594327552","matchMode":0,"sort":1,"enabled":true,"loged":true,"handle":"{\"loadBalance\":\"random\",\"retry\":\"3\",\"timeout\":3000}","conditionDataList":[{"paramType":"uri","operator":"\u003d","paramName":"/","paramValue":"/socket/test"}]}]})`

### Recurrent
ws://127.0.0.1:9195/socket/test
It can connected to gateway side, but I got errors above.It seems can't connect to websocket service side.Is any mistakes I've made?
BTW, I think the doc showed in this link: (https://shenyu.apache.org/zh/docs/plugin-center/proxy/websocket-plugin) is too simple!

**Comment by yu199195** [comment]
WebSocketHandshakeException ， can you check you real server ？ 

> 127.0.0.1:8868

**Comment by PeaceStefanYO** [comment]
> WebSocketHandshakeException ， can you check you real server ？
> 
> > 127.0.0.1:8868

zh46065ml@ZH46065MLdeMacBook-Pro ~ % telnet 127.0.0.1 8868
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.

**Comment by PeaceStefanYO** [comment]
I got the problem, my config mistake, close it!
