### ISSUE TITLE
[BUG] shenyu/plugin/selector/findList error

### ISSUE THREAD

**Issue by ZhangJiaLei123** [apache/incubator-shenyu#3001]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

http://localhost:9195/shenyu/plugin/selector/findList?pluginName=contextPath

### Expected Behavior

get selector list

### Steps To Reproduce

http://localhost:9195/shenyu/plugin/selector/findList?pluginName=contextPath

### Environment

```markdown
ShenYu version(s): master [9413946]


### Debug logs

```log
2022-03-08 14:18:34 [shenyu-netty-nio-2] WARN  org.apache.shenyu.common.utils.JsonUtils - write to json string error: org.apache.shenyu.plugin.api.result.DefaultShenyuEntity@5b627c42
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Direct self-reference leading to cycle (through reference chain: org.apache.shenyu.plugin.api.result.DefaultShenyuEntity["data"]->org.springframework.web.server.ResponseStatusException["mostSpecificCause"])
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77)
	at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1191)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter._handleSelfReference(BeanPropertyWriter.java:944)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:721)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:722)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:166)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:722)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:166)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:4094)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3404)
	at org.apache.shenyu.common.utils.JsonUtils.toJson(JsonUtils.java:85)
	at org.apache.shenyu.plugin.api.result.ShenyuResult.format(ShenyuResult.java:58)
	at org.apache.shenyu.plugin.api.utils.WebFluxResultUtils.result(WebFluxResultUtils.java:58)
	at org.apache.shenyu.web.handler.GlobalErrorHandler.handle(GlobalErrorHandler.java:59)

```
![微信截图_20220308142217](https://user-images.githubusercontent.com/40969169/157178953-f54756c0-6459-4975-b384-d48ac4c16966.png)

**Comment by yu199195** [comment]
hi, can you  config to context path?

**Comment by ZhangJiaLei123** [comment]
this: [issues:2951](https://github.com/apache/incubator-shenyu/issues/2951)
* http://localhost:9195/shenyu/plugin/selectorAndRules 
```json
{
    "pluginName": "contextPath",
    "selectorHandler": "[{\"upstreamUrl\":\"127.0.0.1:8507\"}]",
    "conditionDataList": [{
        "paramType": "uri",
        "operator": "match",
        "paramValue": "/app1/**"
    }],
    "ruleDataList": [{
        "ruleHandler": "{\"loadBalance\":\"random\"}",
        "conditionDataList": [{
            "paramType": "uri",
            "operator": "match",
            "paramValue": "/app1/**"
        }]
    }]
}
```

**Comment by yu199195** [comment]
this is divide plugin，not context path

**Comment by ZhangJiaLei123** [comment]
can i config context_path by curl? can`t set "pluginName": "contextPath" ?

**Comment by yu199195** [comment]
contextPath have not  selectorHandler  and have different ruleHandler， mybe like this ：

```json
{
    "pluginName": "contextPath",
    "conditionDataList": [{
        "paramType": "uri",
        "operator": "match",
        "paramValue": "/app1/**"
    }],
    "ruleDataList": [{
        "ruleHandler": "{\"contextPath\":\"you context path\"}",
        "conditionDataList": [{
            "paramType": "uri",
            "operator": "match",
            "paramValue": "/app1/**"
        }]
    }]
}
```

**Comment by ZhangJiaLei123** [comment]
I set it
* divide config
```json
{
    "pluginName": "divide",
    "selectorHandler": "[{\"upstreamUrl\":\"127.0.0.1:8507\"}]",
    "conditionDataList": [{
        "paramType": "uri",
        "operator": "match",
        "paramValue": "/hnsp/**"
    }],
    "ruleDataList": [{
        "ruleHandler": "{\"loadBalance\":\"random\"}",
        "conditionDataList": [{
            "paramType": "uri",
            "operator": "match",
            "paramValue": "/hnsp/**"
        }]
    }]
}
```
* contextPath config
```
{
    "pluginName": "contextPath",
    "conditionDataList": [{
        "paramType": "uri",
        "operator": "match",
        "paramValue": "/app/**"
    }],
    "ruleDataList": [{
        "ruleHandler": "{\"contextPath\":\"/app\"}",
        "conditionDataList": [{
            "paramType": "uri",
            "operator": "match",
            "paramValue": "/app/**"
        }]
    }]
}
```
I can successed on '127.0.0.1:9195/hnsp/uaccess/logintest', 
failed on '127.0.0.1:9195/app/hnsp/uaccess/logintest'.
error info:
```
{
	"code": -107,
	"message": "divide:Can not find selector, please check your configuration!",
	"data": null
}
```
 
![微信截图_20220311144202](https://user-images.githubusercontent.com/40969169/157816234-527d75ec-02e1-44e5-9d2c-1ec4eed65ca9.png)

**Comment by ZhangJiaLei123** [comment]
thanks. I forgot to set localKey on Header. 
![00C45AC8](https://user-images.githubusercontent.com/40969169/157818106-f8794537-17af-4956-985d-fc55eb213a3b.png)
