### ISSUE TITLE
[BUG] `ReflectUtils#invokeMethod` is no executable object

### ISSUE THREAD

**Issue by li-keguo** [apache/incubator-shenyu#3122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In ReflectUtils has code ....
``` java
    public static Object invokeMethod(final Class<?> clazz, final String method) {
        try {
            Method m = findMethod(clazz, method);
            assert m != null;
            return m.invoke(null);
        } catch (Exception e) {
            LOG.error("", e);
        }
        return null;
    }
```
it not has executable object

`org.apache.shenyu.client.grpc.json.JsonServerCallListener#onMessage`used
```java
    public void onMessage(final R message) {
        Message.Builder builder;
        Class<?> t = JsonServerServiceInterceptor.getRequestClazzMap().get(call.getMethodDescriptor().getFullMethodName());
        try {
            builder = (Message.Builder) ReflectUtils.invokeMethod(t, "newBuilder");

            String reqData = JsonMessage.getDataFromDynamicMessage((DynamicMessage) message);
            JsonFormat.parser().ignoringUnknownFields().merge(reqData, builder);
            if (Objects.isNull(builder)) {
                throw new ShenyuException("build json response message is error, newBuilder method is null");
            }

            delegate.onMessage((R) builder.build());
        } catch (Exception e) {
            LOG.error("handle json generic request is error", e);
            throw Status.INTERNAL.withDescription(e.getMessage()).asRuntimeException();
        }
    }
```

### Environment

```markdown
ShenYu version(s):master
```

### Debug logs

```log
11:33:34.531 [main] ERROR org.apache.shenyu.common.utils.ReflectUtils - 
java.lang.NullPointerException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.shenyu.common.utils.ReflectUtils.invokeMethod(ReflectUtils.java:103)
null
```

**Comment by LiuTianyou** [comment]
Can I try to fix this bug?

**Comment by li-keguo** [comment]
ok!
