### ISSUE TITLE
[BUG] TimingWheel ArrayIndexOutOfBoundsException, problem caused by long to int

### ISSUE THREAD

**Issue by jerbo99** [apache/incubator-shenyu#3296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There are some ArrayIndexOutOfBoundsException in the logs of the admin and bootstrap.

### Steps To Reproduce

Download the binary package and launch. I will fix it

### Environment

```markdown
ShenYu version(s): 2.4.3
```

### Debug logs

java.lang.ArrayIndexOutOfBoundsException: -18
        at org.apache.shenyu.common.timer.TimingWheel.getBucket(TimingWheel.java:116)
        at org.apache.shenyu.common.timer.TimingWheel.add(TimingWheel.java:88)
        at org.apache.shenyu.common.timer.HierarchicalWheelTimer.addTimerTaskEntry(HierarchicalWheelTimer.java:104)
        at org.apache.shenyu.common.timer.TimerTaskList.flush(TimerTaskList.java:78)
        at org.apache.shenyu.common.timer.HierarchicalWheelTimer.advanceClock(HierarchicalWheelTimer.java:119)
        at org.apache.shenyu.common.timer.HierarchicalWheelTimer$Worker.run(HierarchicalWheelTimer.java:164)
        at java.lang.Thread.run(Thread.java:748)

**Comment by yu199195** [comment]
What scenario would lead to this?

**Comment by jerbo99** [comment]
The absence of parentheses here results in negative numbers:

long virtualId = expirationMs / tickMs;
int index = (int) virtualId % wheelSize;

发件人: ***@***.***>
发送时间: 2022年4月22日 14:12
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [apache/incubator-shenyu] [BUG] TimingWheel ArrayIndexOutOfBoundsException, problem caused by long to int (Issue #3296)


What scenario would lead to this?

―
